# Generated by Django 3.1 on 2020-08-17 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200816_1839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
